name: sp_client
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.15.7
  intl_translation: ^0.17.2
  collection: ^1.14.11
  equatable: ^0.1.0
  rxdart: ^0.20.0
  bloc: ^0.9.3
  flutter_bloc: ^0.7.0
  sqflite: ^1.0.0
  image_picker: ^0.4.10
  outline_material_icons: ^0.1.0
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true