name: sp_client
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.3.0-dev.0.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.15.7
  intl_translation: ^0.17.2
  collection: ^1.14.11
  equatable: ^0.2.3
  http: 0.12.0+1
  rxdart: ^0.22.0
  bloc: ^0.14.2
  flutter_bloc: ^0.16.0
  shared_preferences: ^0.5.2+1
  outline_material_icons: ^0.1.0
  cupertino_icons: ^0.1.2
  grpc: ^1.0.2
  protobuf: ^0.13.11
  uuid: ^2.0.1
  # Firebase
  firebase_core: ^0.4.0+3
  firebase_database: ^3.0.2
  firebase_analytics: ^3.0.2
  # Plugins
  share: ^0.6.1+1
  sqflite: ^1.1.5
  image_picker: ^0.6.0+3
  path_provider: ^1.1.0
  package_info: ^0.4.0+3
  device_info: ^0.4.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true