name: fill_memo
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.3.0-dev.0.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.16.0
  intl_translation: ^0.17.5
  collection: ^1.14.11
  equatable: ^0.4.0
  http: ^0.12.0+2
  flutter_bloc: ^0.20.0
  shared_preferences: ^0.5.3+4
  outline_material_icons: ^0.1.0
  material_design_icons_flutter: ^3.2.4096
  grpc: ^2.0.0+1
  protobuf: ^0.13.15
  uuid: ^2.0.2
  flutter_staggered_grid_view: ^0.3.0
  cached_network_image: ^1.1.1
  flutter_material_color_picker: ^1.0.2
  flutter_markdown: ^0.2.0
  rich_text_editor:
    git:
      url: https://github.com/namhyun-gu/flutter_rich_text_editor
  # Firebase
  firebase_core: ^0.4.0+8
  firebase_storage: ^3.0.5
  firebase_analytics: ^4.0.2
  firebase_performance: ^0.3.0+4
  firebase_crashlytics: ^0.1.0+2
  firebase_auth: ^0.14.0
  cloud_firestore: ^0.12.9
  # Plugins
  image_picker: ^0.6.1
  package_info: ^0.4.0+6
  device_info: ^0.4.0+2
  local_auth:
    path: packages/local_auth
  path_provider: ^1.3.0
  permission: ^0.1.2
  # Web packages
  firebase: ^5.0.4
  universal_html: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - res/images/
  fonts:
    - family: NotoSansKR
      fonts:
        - asset: res/fonts/NotoSansKR-Regular.otf
        - asset: res/fonts/NotoSansKR-Medium.otf
        - asset: res/fonts/NotoSansKR-Bold.otf
